-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,'%Y-%m-%d') as START_DATE, DATE_FORMAT(END_DATE,'%Y-%m-%d') as END_DATE, if(DATEDIFF(END_DATE , START_DATE) >= 29, '장기 대여','단기 대여') as RENT_TYPE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where YEAR(START_DATE) = 2022 and MONTH(START_DATE) = 9
order by HISTORY_ID DESC

/* TIMESTAMPDIFF(단위,시작시간,끝시간) -> 사이 단위 구해줌*/