-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID)
from CAR_RENTAL_COMPANY_CAR as A join CAR_RENTAL_COMPANY_RENTAL_HISTORY as B on A.CAR_ID = B.CAR_ID
where CAR_TYPE = '세단' and MONTH(START_DATE) = 10
order by CAR_ID DESC